#+TITLE: Meup.org
#+DESCRIPTION: Python script to get things done
#+AUTHOR: Léo "pi^2/6" Perrin <leoperrin@picarresursix.fr>
#+DATE: Time-stamp: <2013-05-14 12:35:40 leo>
#+STARTUP: hidestars indent align





* Project description
!INCLUDE! py$ md$
!EXCLUDE! pdf pyc test el png

* Items directories                                                      :md:
** ./readme.md [[././readme.md][=>]] 
1. M: [[file:./readme.md::3][link]]
** ./templates [[././templates][=>]] 
*** meuporg.md [[././templates/meuporg.md][=>]] 
1. INCLUDE: [[file:./templates/meuporg.md::18][link]]
2. EXCLUDE: [[file:./templates/meuporg.md::19][link]]
* [0/3] python
The aim of this script is to list the items in a directory, to sort
them, to present them in a nice way and to update a file using them.
** Useful links
+ [[http://docs.python.org/2/howto/regex.html][Documentation]] of the re module for regexps in python
+ [[http://docs.python.org/2/library/os.path.html][Documentation]] of the os.path module for python
+ [[** TODO Implement statistics][Documentation]] of the argparse module
** TODO Add possibility of adding structural items
When writing code (not LaTeX), it might be nice to be able to add
SECTION, SUBSECTION etc. items. Then, adding a heading "structure"
in the main file would create a tree:
directory tree/file/section/subsection.

It might be nice to skip the directory tree part if there is less
than, say, 10 files. Or add a special command between parenthesis?
** TODO Add time-stamp
Python code to print time-stamp:
#+begin_src python
  import datetime
  print datetime.datetime.today().strftime("%A, %d. %B %Y %I:%M%p")
#+end_src
output: "Friday, 25. January 2013 09:50AM".
** TODO Add support for git
Dependency: python-git
Documentation: [[http://packages.python.org/GitPython/0.3.1/tutorial.html][tuto (official website)]]
#+begin_src python
  from git import *

  for x in repo.commits():
      print "** {}\n".format(x.message)
#+end_src
* [1/1] Documentation
** DONE [[file:doc/description.org][description.org]]
CLOSED: [2013-01-24 jeu. 12:39]
* [1/1] emacs
A minor-mode providing an interface to easily use items in text files
and to call the python script directly from emacs. It is written using
literate programming with org-babel.
** [[file:emacs-mode/meuporg-mode.org][meuporg-mode.org]] (code file)
** Links used
*** Have buttons? [[http://stackoverflow.com/questions/7696208/emacs-lisp-how-to-add-to-link-hyperlink-to-another-file-just-like-that-in-h-e][example]]
*** Open buffer in new frame: [[http://ftp.gnu.org/old-gnu/Manuals/elisp-manual-21-2.8/html_node/elisp_433.html][pop-to-buffer]]
*** Obtain the full path to the current file
The lisp code is
#+begin_src el
 (expand-file-name (buffer-file-name))
#+end_src
I built it from the [[http://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer-File-Name.html][buffer file name documentation]] and the
[[http://www.gnu.org/software/emacs/manual/html_node/elisp/File-Name-Expansion.html#File-Name-Expansion][file name documentation]].
*** Concept of [[http://www.chemie.fu-berlin.de/chemnet/use/info/elisp/elisp_28.html][excursion]].
*** Remove the read-only property of a buffer to modify it
[[http://www.chemie.fu-berlin.de/chemnet/use/info/elisp/elisp_25.html#SEC360][source]].
#+begin_src lisp
  (setq inhibit-read-only t)
#+end_src

*** Save all the buffers
[[http://www.chemie.fu-berlin.de/chemnet/use/info/elisp/elisp_23.html#SEC323][source]]
